name: web_app
description: The AngularDart version of https://github.com/Shinpeim/NekogataDrumSequencer
version: 0.0.1
environment:
  sdk: '>=1.23.0 <2.0.0'
dependencies:
  angular2: ^3.0.0
  angular_components: ^0.5.0
  model:
    path: ../model
dev_dependencies:
  browser: ^0.10.0
  dart_to_js_script_rewriter: ^1.0.1
transformers:
- angular2:
    platform_directives:
    - 'package:angular2/common.dart#COMMON_DIRECTIVES'
    platform_pipes:
    - 'package:angular2/common.dart#COMMON_PIPES'
    entry_points: web/main.dart
- dart_to_js_script_rewriter
